default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV.fetch("DB_USERNAME", "naresh") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Naresh@14356") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: practial_softices_development

test:
  <<: *default
  database: practial_softices_test

production:
  <<: *default
  database: practial_softices_production
