default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>

development:
  <<: *default
  database: practial_softices_development

test:
  <<: *default
  database: practial_softices_test

production:
  <<: *default
  database: practial_softices_production
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
